### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by bju2000** [maruos/platform_prebuilts_busybox#1]
[701/1103] including ./prebuilts/busybox/Android.mk ...
build/core/module_arch_supported.mk:50: warning: busybox: architecture arm64 not supported

There's a problem like this. Can I use this?
https://github.com/LineageOS/android_external_busybox

**Comment by pdsouza** [comment]
@bju2000 That warning is harmless since the arm binary runs fine on arm64
